# Generated by Django 4.2.2 on 2023-06-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
