# Generated by Django 4.2.2 on 2023-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_alter_licenseapplication_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Declined', 'Declined'), ('Approved - (Pending Payment)', 'Approved (Pending Payment)'), ('Approved - (Paid)', 'Approved (Paid)')], default='Pending', max_length=50),
        ),
    ]
