# Generated by Django 4.2.2 on 2023-09-14 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_licenseapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenseapplication',
            name='address',
        ),
    ]
